# Each piece within the #'s could theoretically be its own machine. But it could also operate just on one big machine.
# Right now things are linked through docker. If we dploy with something else that doesn't respect links, thing will have to be refactored.
# Things could be factored as Minions being indivdiual machines and everything else goes on a master machine.

######## CADVISOR #########
cadvisor:
  image: google/cadvisor:latest
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - "0.0.0.0:8888:8080"
####################################


######## MINION MACHINE #########
minionredis:
  image: redis
  command: redis-server /next_backend/next/database/redis.conf
  volumes:
   - .:/next_backend
  expose:
   - "6379"

minionworker:
  build: next/base_docker_image
  command: ./next/broker/next_worker_startup.sh
  volumes:
   - .:/next_backend
  working_dir: /next_backend
  links:
    - mongodb:MONGODB
    - rabbitmq:RABBIT
    - rabbitmqredis:RABBITREDIS
    - minionredis:MINIONREDIS
  environment:
   - PYTHONUNBUFFERED=TRUE
   - CELERY_SYNC_WORKER_COUNT={{CELERY_SYNC_WORKER_COUNT}}
   - CELERY_ASYNC_WORKER_COUNT={{CELERY_ASYNC_WORKER_COUNT}}
   - CELERY_THREADS_PER_ASYNC_WORKER={{CELERY_THREADS_PER_ASYNC_WORKER}}
   - CELERY_ASYNC_WORKER_PREFETCH={{CELERY_ASYNC_WORKER_PREFETCH}}
   - CELERY_DASHBOARD_WORKER_COUNT={{CELERY_DASHBOARD_WORKER_COUNT}}
   - CELERY_THREADS_PER_DASHBOARD_WORKER={{CELERY_THREADS_PER_DASHBOARD_WORKER}}
   - CELERY_DASHBOARD_WORKER_PREFETCH={{CELERY_DASHBOARD_WORKER_PREFETCH}}
   - SITE_KEY
   - GIT_HASH={{GIT_HASH}}
   - PYTHONPATH=:/next_backend
####################################


######### API #########
nextbackenddocker:
  build: next/base_docker_image
  command: gunicorn  --reload --worker-class=gevent -R --log-level=debug --logger-class=simple --max-requests={{NEXT_BACKEND_GUNICORN_WORKER_MAX_REQUESTS}} -b 0.0.0.0:8000 -w {{NEXT_BACKEND_NUM_GUNICORN_WORKERS}} next.api.api:app
  volumes:
   - .:/next_backend
  working_dir: /next_backend
  ports:
    - "0.0.0.0:{{NEXT_BACKEND_GLOBAL_PORT}}:8000" # gunicorn
  links:
    # - miniondatabasedocker:MINIONDATABASESERVER  # right now the API makes database calls within the container to retrieve logs. This is bad! This work should be thrown on a queue and given to workers to do
    - rabbitmq:RABBIT
    - rabbitmqredis:RABBITREDIS
    - mongodb:MONGODB
    - minionworker:MINIONWORKER
    - minionredis:6379
  environment:
   - PYTHONUNBUFFERED=TRUE
   - PYTHONPATH=:/next_backend
   # global url for dashboards on backend
   - NEXT_BACKEND_GLOBAL_HOST
   - NEXT_BACKEND_GLOBAL_PORT
   - SITE_KEY
   - GIT_HASH={{GIT_HASH}}
   - TERM=xterm
   - CELERY_ON={{CELERY_ON}}
####################################



######### PERSISTENT STORE #########
mongodb:
  image: mongo:3.4
  ports:
   - "0.0.0.0:28017:28017" # mongo http monitor
####################################


######### RABBITMQ #########
rabbitmq:
  image: rabbitmq:3-management
  ports:
   - "0.0.0.0:15672:15672"

rabbitmqredis:
  image: redis
###########################


